services:
  - type: web
    name: movie-sentiment-api
    env: python
    buildCommand: |
      apt-get update -y
      apt-get install -y build-essential python3-dev libatlas-base-dev
      pip install numpy
      pip install -r requirements.txt
    startCommand: gunicorn app:app
