services:
  - type: web
    name: movie-sentiment-api
    env: python
    buildCommand: |
      cd backend
      apt-get update -y
      apt-get install -y build-essential python3-dev libatlas-base-dev gfortran
      pip install gunicorn
      pip install -r requirements.txt
    startCommand: gunicorn backend.app:app

